dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x0a87e12689374A4EF49729582B474a1013cceBf8'
    verify: False
  mainnet-fork-dev:
    eth_usd_price_feed: '0x0a87e12689374A4EF49729582B474a1013cceBf8'
    verify: False
  development:
    verify: False
  kovan:
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
  mainnet:
    eth_usd_price_feed: '0x0a87e12689374A4EF49729582B474a1013cceBf8'
  ganache-local-two:
    verify: False
